"""add genre_tag_embedding to tracks

Revision ID: 0727e0f39752
Revises: d1ee92fd2f58
Create Date: 2026-07-14 10:36:32.555487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0727e0f39752'
down_revision: Union[str, None] = 'd1ee92fd2f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('genre_tag_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'genre_tag_embedding')
    # ### end Alembic commands ###
