"""add silhouette score to clustering runs

Revision ID: d1ee92fd2f58
Revises: 7dfdde0d288a
Create Date: 2026-07-07 20:28:12.392834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ee92fd2f58'
down_revision: Union[str, None] = '7dfdde0d288a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clustering_runs', sa.Column('silhouette_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clustering_runs', 'silhouette_score')
    # ### end Alembic commands ###
